export { default as Play } from "./Play.png";
export { default as Pause } from "./Pause.png";
export { default as Stop } from "./Stop.png";
export { default as Back } from "./Back.png";
export { default as Forward } from "./Forward.png";
export { default as Fullscreen } from "./Fullscreen.png";
export { default as Font } from "./Font.png";
export { default as Upload } from "./Upload.png";
export { default as Wave } from "./Wave";
